name: Rarotonga
favicon: null
layout_spectrum: 0.8729080248158425
typography_spectrum: 0.2987066812347621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.910316571360454
  lightness: 0.950526074739173
  saturation: 0.04934945632703602
  rhythmicContrast: 0.986543596489355
purpose: []
